### ISSUE TITLE
GPIO Library 

### ISSUE THREAD

**Issue by sjpark608** [EdgePi-Cloud/edgepi-python-sdk#20]
There are two types of GPIOs on the EdgePi.

1. BCM MCU GPIOs that are controlled directly by the kernel
   - DIN1-8, DOUT1-2, IO_RST, SPARE1, SPARE2
2. GPIO expanders that are controlled using I2C comm
   - DOUT3-8,  RTD_EN,  DAC_GAIN, LED_OVR1-8, AN_EN1-8, GNDSW_IN1, GNDSW_IN2, RELAY_EN

Modules
1. Terminal block configuration
   - Analog/Digital input
   - Analog/Digital output
2. LED indicator 

## TODOs:
- [x] #86
- [x] Data classes for GPIO registers of both expander chips
- [x] peripherals required
   - [x] GPIO
   - [x] I2C it will inherit I2C to perform I2C transactions
- [x] Contain default information of each GPIO pins 

### edgepi_gpio
- [x] #48
   - [x] gpio only requires I2C periph
      - [x] #49
      - [x] LED array
      - [x] ADC
      - [x] RTD
   - [x] gpio only requires GPIO periph -> using gpiochip device
      - [ ] Digital Input
   - [x] gpio requires both I2C and GPIO
      - [ ] Digital Output 

### gpio_commands
- [x] #51
- [x] #52
- [x] #50
   - [ ] Set GPIO to the know default states, refer to issue #21 

### gpio_constants
- [ ] have GPIO config 
- [x] #40
- [x] adc
- [x] rtd
- [ ] dout
- [ ] din
- [x] ledarray
- [x] I2C message configs
   - [x] addresses
   - [x] register configs
   - [x] register opcodes 

### Default values
- [x] #21
